/*

	Lilact
	Copyright (C) 2024-2026 Arash Kazemi <contact.arash.kazemi@gmail.com>
	All rights reserved.

	BSD-2-Clause

	Redistribution and use in source and binary forms, with or without
	modification, are permitted provided that the following conditions are met:

	* Redistributions of source code must retain the above copyright
		notice, this list of conditions and the following disclaimer.
	* Redistributions in binary form must reproduce the above copyright
		notice, this list of conditions and the following disclaimer in the
		documentation and/or other materials provided with the distribution.

	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
	AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
	IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
	ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
	DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
	(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
	LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
	ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
	(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
	THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/
/*
Lilact
Copyright (C) 2024-2026 Arash Kazemi
BSD-2-Clause
*/

import Lilact from "./lilact.jsx";
import { required_scripts } from "./run.jsx";
import { css } from "@emotion/css";

function numberOrNull(value) {
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

function firstNumber(...values) {
  for (const value of values) {
    const n = numberOrNull(value);
    if (n !== null) return n;
  }
  return null;
}

function asError(value) {
  if (value instanceof Error) return value;

  if (value && typeof value === "object") {
    if (value.error instanceof Error) return value.error;

    const error = new Error(
      value.message == null ? String(value) : String(value.message)
    );

    if (value.name) error.name = value.name;
    if (value.stack) error.stack = value.stack;

    for (const key of Object.keys(value)) {
      if (!(key in error)) error[key] = value[key];
    }

    return error;
  }

  return new Error(String(value));
}

function isParserError(error) {
  return  error?.name === "JSXParserError";
}

/*
Returns zero-based line and column numbers.

Parser errors produced by jsx.js already use zero-based positions.
Browser Error objects and ErrorEvents normally use one-based positions.
*/
function getErrorLocation(error, { zeroBased = false } = {}) {
  const line = firstNumber(
    error?.lineNumber,
    error?.lineno,
    error?.line
  );

  const column = firstNumber(
    error?.columnNumber,
    error?.colno,
    error?.column
  );

  if (line !== null || column !== null) {
    return {
      line:
        line === null
          ? null
          : zeroBased
            ? line
            : Math.max(0, line - 1),

      col:
        column === null
          ? null
          : zeroBased
            ? column
            : Math.max(0, column - 1),
    };
  }

  return null;
}

function sourceUrlFromStack(stack) {
  const text = typeof stack === "string" ? stack : "";

  /*
   * The final two colon-separated numeric values are the line and column.
   * The path is intentionally greedy so paths containing ':' still work.
   *
   * Examples:
   *
   *   at fn (eval:/components/App.jsx:12:8)
   *   fn@eval:/components/App.jsx:12:8
   *   eval:/components/App.jsx:12:8
   */
  const expression = /(?:^|[\s(@])((?:eval:\/)[\s\S]*):(\d+):(\d+)(?:\)?$)/;

  for (const line of text.split(/\r?\n/)) {
    const match = line.trim().match(expression);
    if (!match) continue;

    return {
      url: match[1],
      line: Number(match[2]),
      col: Number(match[3]),
    };
  }

  return null;
}

function sourcePathFromEvalUrl(url) {
  if (typeof url !== "string") return null;

  if (url.startsWith("eval:/")) {
    return url.slice("eval:/".length);
  }

  if (url.startsWith("eval:")) {
    return url.slice("eval:".length).replace(/^\/+/, "");
  }

  return null;
}

/*
Mappings generated by jsx.js have this shape:

[
  generatedLine,
  generatedColumn,
  sourceLine,
  sourceColumn,
  node
]

All four coordinates are zero-based.

The correct mapping is the closest mapping at or before the generated
location. The old implementation searched in the opposite direction and
used the final mapping for errors occurring before the first mapping.
*/
export function mapLocation(mappings, generatedLine, generatedColumn) {
  if (!Array.isArray(mappings) || mappings.length === 0) {
    return {
      line: generatedLine,
      col: generatedColumn,
    };
  }

  const line = Number(generatedLine);
  const col = Number(generatedColumn);

  if (!Number.isFinite(line) || !Number.isFinite(col)) {
    return {
      line: null,
      col: null,
    };
  }

  const validMappings = mappings
    .filter(
      (mapping) =>
        Array.isArray(mapping) &&
        mapping.length >= 4 &&
        Number.isFinite(Number(mapping[0])) &&
        Number.isFinite(Number(mapping[1])) &&
        Number.isFinite(Number(mapping[2])) &&
        Number.isFinite(Number(mapping[3]))
    )
    .slice()
    .sort((a, b) => {
      const lineDifference = Number(a[0]) - Number(b[0]);

      if (lineDifference !== 0) {
        return lineDifference;
      }

      return Number(a[1]) - Number(b[1]);
    });

  if (validMappings.length === 0) {
    return {
      line,
      col,
    };
  }

  /*
   * Find the last mapping whose generated position is before or equal
   * to the runtime position.
   */
  let mapping = validMappings[0];

  for (const candidate of validMappings) {
    const generatedMappingLine = Number(candidate[0]);
    const generatedMappingColumn = Number(candidate[1]);

    if (
      generatedMappingLine < line ||
      (
        generatedMappingLine === line &&
        generatedMappingColumn <= col
      )
    ) {
      mapping = candidate;
      continue;
    }

    break;
  }

  const mappingGeneratedLine = Number(mapping[0]);
  const mappingGeneratedColumn = Number(mapping[1]);
  const mappingSourceLine = Number(mapping[2]);
  const mappingSourceColumn = Number(mapping[3]);

  /*
   * A mapping points to the beginning of a generated region. Preserve
   * the relative line offset inside that region.
   *
   * This is the important part. Returning mappingSourceLine directly
   * causes errors inside a generated multi-line block to point to the
   * first line of the block.
   */
  const sourceLine =
    mappingSourceLine + (line - mappingGeneratedLine);

  /*
   * Columns are only safely relative when the generated error is on the
   * same generated line as the mapping. On later lines, use the source
   * anchor column instead of carrying the generated column across lines.
   */
  const sourceColumn =
    line === mappingGeneratedLine
      ? Math.max(
          0,
          mappingSourceColumn +
            (col - mappingGeneratedColumn)
        )
      : mappingSourceColumn;

  return {
    line: sourceLine,
    col: sourceColumn,
  };
}

function getBlockTrace(error) {
  const trace = error?.lilact_trace;

  if (Array.isArray(trace)) {
    return trace[0];
  }

  return trace;
}

function getBlockInfo(error) {
  const trace = getBlockTrace(error);

  if (trace === undefined || trace === null) {
    return null;
  }

  return Lilact.blocks_info?.labels?.[trace] ?? null;
}

function applyBlockFallback(error, result, currentPath) {
  const block = getBlockInfo(error);
  if (!block) return result;

  if (block.path) {
    result.fileName = block.path;
  } else if (!result.fileName) {
    result.fileName = currentPath;
  }

  /*
   * scanBlockLabels() stores the original source position of the block.
   * This is more reliable than using the location of the generated catch
   * wrapper.
   */
  if (
    Number.isFinite(block.line) &&
    Number.isFinite(block.col)
  ) {
    result.lineNumber = block.line;
    result.columnNumber = block.col;
  }

  if (block.desc) {
    result.label = block.desc;
  }

  return result;
}

function copyErrorMetadata(source, target) {
  if (!source || typeof source !== "object") return;

  for (const key of [
    "fileName",
    "lineNumber",
    "columnNumber",
    "lineno",
    "colno",
    "line",
    "column",
    "componentStackLog",
    "lilact_trace",
  ]) {
    if (source[key] !== undefined && target[key] === undefined) {
      target[key] = source[key];
    }
  }
}

/**
 * Converts parser errors, runtime errors, ErrorEvents, and rejected
 * promises into one consistent zero-based representation.
 */
export function traceError(value, runPath) {
  if (value?.isTraced) return value;

  const original =
    value?.error instanceof Error ? value.error : asError(value);

  const parserError = isParserError(original);

  const stackLocation = parserError
    ? null
    : sourceUrlFromStack(original.stack);

  const eventLocation = parserError
    ? getErrorLocation(original, { zeroBased: true })
    : getErrorLocation(original);

  const result = {
    fileName:
      sourcePathFromEvalUrl(stackLocation?.url) ||
      original.fileName ||
      runPath ||
      null,

    lineNumber:
      stackLocation?.line != null
        ? Math.max(0, stackLocation.line - 1)
        : eventLocation?.line ?? null,

    columnNumber:
      stackLocation?.col != null
        ? Math.max(0, stackLocation.col - 1)
        : eventLocation?.col ?? null,

    message:
      original.message == null
        ? String(original)
        : String(original.message),

    name: original.name || "Error",
    stack: original.stack || null,
    _error: original,
    isTraced: true,
  };

  copyErrorMetadata(value, result);
  copyErrorMetadata(original, result);

  /*
   * Parser errors already point into the original JSX source. Do not map
   * them again.
   */
  if (!parserError && stackLocation?.url) {
    const module = required_scripts[result.fileName];

    if (module?.mappings) {
      const mapped = mapLocation(
        module.mappings,
        result.lineNumber,
        result.columnNumber
      );

      result.lineNumber = mapped.line;
      result.columnNumber = mapped.col;
    }
  }

  /*
   * When the browser does not preserve the eval sourceURL, the injected
   * Lilact block label is the reliable fallback.
   */
  if (!parserError && !stackLocation?.url) {
    applyBlockFallback(original, result, runPath);
  }

  Lilact.error = result;
  return result;
}

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function sourceExcerpt(module, zeroBasedLine) {
  if (!module || !Number.isFinite(zeroBasedLine)) {
    return null;
  }

  const lines = String(module.code ?? "").split(/\r?\n/);
  const before = lines[zeroBasedLine - 1] ?? "";
  const current = lines[zeroBasedLine] ?? "";
  const after = lines[zeroBasedLine + 1] ?? "";

  return { before, current, after };
}

/**
 * Displays an unhandled error.
 */
export function globalErrorHandler(eventOrError) {
  const raw =
    eventOrError?.error instanceof Error
      ? eventOrError.error
      : eventOrError?.reason !== undefined
        ? eventOrError.reason
        : eventOrError;

  const runPath =
    eventOrError?.fileName ||
    null;

  const traced = traceError(raw, runPath);
  const module = required_scripts[traced.fileName];
  const excerpt = sourceExcerpt(module, traced.lineNumber);

  const className = css(`
    background: linear-gradient(135deg, #fff2f2d4, #ffffffd4);
    backdrop-filter: blur(10px);
    border: 1px solid rgba(255,255,255,.25);
    border-radius: 5px;
    box-shadow: 0 10px 30px rgba(0,0,0,.35);
    overflow: hidden;
    min-width: 400px;
    width: 66%;

    red {
      color: #d00;
    }

    code {
      border: 1px solid #0003;
      overflow: auto;
      padding: 10px;
      display: block;
    }
  `);

  const dialog = document.createElement("dialog");
  dialog.className = className;

  const location =
    traced.fileName
      ? `At ${escapeHtml(traced.fileName)}`
      : "";

  const line =
    Number.isFinite(traced.lineNumber)
      ? `: Line ${traced.lineNumber + 1}`
      : "";

  const componentStack =
    traced._error?.componentStackLog ||
    traced._error?.componentStack ||
    "";

  dialog.innerHTML = `
    <h3><red>Error!</red></h3>
    <b>${location}${line}</b><br><br>
    <b>${escapeHtml(traced.name)}</b>:
    <span>${escapeHtml(traced.message)}</span>
    <br><br>

    ${
      excerpt
        ? "<code><pre></pre><red><pre></pre></red><pre></pre></code>"
        : ""
    }

    ${
      componentStack
        ? `
          <br>
          Component Stack:
          <br>
          <code><pre>${escapeHtml(componentStack)}</pre></code>
        `
        : ""
    }
  `;

  if (excerpt) {
    const pre = dialog.querySelectorAll("pre");
    pre[0].innerText = excerpt.before;
    pre[1].innerText = excerpt.current;
    pre[2].innerText = excerpt.after;
  }

  document.body.appendChild(dialog);

  if (typeof dialog.showModal === "function") {
    dialog.showModal();
  } else {
    dialog.setAttribute("open", "");
  }

  return traced;
}

/**
 * Registers the source location of an injected Lilact block.
 */
export function scanBlockLabels(code, path) {
  const labels = String(code).matchAll(
    /LILACTBLOCK(\d+):(\d+),(\d+):([^*]+)\*\//gm
  );

  for (const match of labels) {
    const id = match[1];

    Lilact.blocks_info.labels[id] = {
      path,
      line: Number(match[2]),
      col: Number(match[3]),
      desc: match[4],
    };
  }
}

export const blocks_info = {
  counter: 0,
  labels: {},
};

export let error = null;
